---
openapi: 3.0.3
info:
  title: Sample specification for the translating parser
  version: 0.0.0
paths:
  /hosts:
    get:
      responses:
        default:
          description: A local reference
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlainObject'
        '200':
          description: A file reference from the root document
          content:
            application/json:
              schema:
                $ref: 'schemas.yaml#/$defs/PlainObject'
components:
  schemas:
    PlainObject:
      type: object
