---
openapi: 3.0.3
info:
  title: Sample specification for the translating parser
  version: 0.0.0
paths:
  /hosts:
    get:
      responses:
        default:
          description: A local reference
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlainObject'
        '200':
          description: A file reference of a simple object from the root document
          content:
            application/json:
              schema:
                $ref: 'schemas_non_recursive.spec.yaml#/$defs/PlainObject'
        '201':
          description: A file reference of a complex object from the root document
          content:
            application/json:
              schema:
                  $ref: 'schemas_non_recursive.spec.yaml#/$defs/ComplexObject'
        '400':
          description: A file reference of a recursive object from the root document
          content:
            application/json:
              schema:
                $ref: 'schemas_non_recursive.spec.yaml#/$defs/RootObject'
components:
  schemas:
    PlainObject:
      type: object
